// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.example.piliplus.AndroidHelper$Companion`
extension type AndroidHelper$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/piliplus/AndroidHelper$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AndroidHelper$Companion> type =
      $AndroidHelper$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AndroidHelper$Companion(
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<AndroidHelper$Companion>();
  }
}

extension AndroidHelper$Companion$$Methods on AndroidHelper$Companion {
  static final _id_get$isFoldable = AndroidHelper$Companion._class
      .instanceMethodId(
        r'isFoldable',
        r'()Z',
      );

  static final _get$isFoldable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final boolean isFoldable()`
  core$_.bool get isFoldable {
    final _$$selfRef = reference;
    return _get$isFoldable(
      _$$selfRef.pointer,
      _id_get$isFoldable.pointer,
    ).boolean;
  }

  static final _id_set$foldable = AndroidHelper$Companion._class
      .instanceMethodId(
        r'setFoldable',
        r'(Z)V',
      );

  static final _set$foldable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public final void setFoldable(boolean z)`
  set foldable(core$_.bool z) {
    final _$$selfRef = reference;
    _set$foldable(
      _$$selfRef.pointer,
      _id_set$foldable.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_back = AndroidHelper$Companion._class.instanceMethodId(
    r'back',
    r'()V',
  );

  static final _back =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun back(): kotlin.Unit`
  void back() {
    final _$$selfRef = reference;
    _back(_$$selfRef.pointer, _id_back.pointer).check();
  }

  static final _id_biliSendCommAntifraud = AndroidHelper$Companion._class
      .instanceMethodId(
        r'biliSendCommAntifraud',
        r'(IJIJJJJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)V',
      );

  static final _biliSendCommAntifraud =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun biliSendCommAntifraud(action: kotlin.Int, oid: kotlin.Long, type: kotlin.Int, rpId: kotlin.Long, root: kotlin.Long, parent: kotlin.Long, ctime: kotlin.Long, commentText: kotlin.String, pictures: kotlin.String?, sourceId: kotlin.String, uid: kotlin.Long, cookie: kotlin.String): kotlin.Unit`
  void biliSendCommAntifraud(
    core$_.int i,
    core$_.int j,
    core$_.int i1,
    core$_.int j1,
    core$_.int j2,
    core$_.int j3,
    core$_.int j4,
    jni$_.JString string,
    jni$_.JString? string1,
    jni$_.JString string2,
    core$_.int j5,
    jni$_.JString string3,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    _biliSendCommAntifraud(
      _$$selfRef.pointer,
      _id_biliSendCommAntifraud.pointer,
      i,
      j,
      i1,
      j1,
      j2,
      j3,
      j4,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      j5,
      _$string3.pointer,
    ).check();
  }

  static final _id_openLinkVerifySettings = AndroidHelper$Companion._class
      .instanceMethodId(
        r'openLinkVerifySettings',
        r'()V',
      );

  static final _openLinkVerifySettings =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun openLinkVerifySettings(): kotlin.Unit`
  void openLinkVerifySettings() {
    final _$$selfRef = reference;
    _openLinkVerifySettings(
      _$$selfRef.pointer,
      _id_openLinkVerifySettings.pointer,
    ).check();
  }

  static final _id_openMusic = AndroidHelper$Companion._class.instanceMethodId(
    r'openMusic',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z',
  );

  static final _openMusic =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun openMusic(title: kotlin.String, artist: kotlin.String?, album: kotlin.String?): kotlin.Boolean`
  core$_.bool openMusic(
    jni$_.JString string,
    jni$_.JString? string1,
    jni$_.JString? string2,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    return _openMusic(
      _$$selfRef.pointer,
      _id_openMusic.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
    ).boolean;
  }

  static final _id_setPipAutoEnterEnabled = AndroidHelper$Companion._class
      .instanceMethodId(
        r'setPipAutoEnterEnabled',
        r'(ZJ)V',
      );

  static final _setPipAutoEnterEnabled =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int64)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public fun setPipAutoEnterEnabled(autoEnable: kotlin.Boolean, engineId: kotlin.Long): kotlin.Unit`
  void setPipAutoEnterEnabled(
    core$_.bool z,
    core$_.int j,
  ) {
    final _$$selfRef = reference;
    _setPipAutoEnterEnabled(
      _$$selfRef.pointer,
      _id_setPipAutoEnterEnabled.pointer,
      z ? 1 : 0,
      j,
    ).check();
  }

  static final _id_maxScreenSize = AndroidHelper$Companion._class
      .instanceMethodId(
        r'maxScreenSize',
        r'()[I',
      );

  static final _maxScreenSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun maxScreenSize(): kotlin.IntArray?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JIntArray? maxScreenSize() {
    final _$$selfRef = reference;
    return _maxScreenSize(
      _$$selfRef.pointer,
      _id_maxScreenSize.pointer,
    ).object<jni$_.JIntArray?>();
  }
}

final class $AndroidHelper$Companion$Type$
    extends jni$_.JType<AndroidHelper$Companion> {
  @jni$_.internal
  const $AndroidHelper$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/piliplus/AndroidHelper$Companion;';
}

/// from: `com.example.piliplus.AndroidHelper$ToDart$Companion`
extension type AndroidHelper$ToDart$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/piliplus/AndroidHelper$ToDart$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AndroidHelper$ToDart$Companion> type =
      $AndroidHelper$ToDart$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AndroidHelper$ToDart$Companion(
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<AndroidHelper$ToDart$Companion>();
  }
}

extension AndroidHelper$ToDart$Companion$$Methods
    on AndroidHelper$ToDart$Companion {
  static final _id_get$onUserLeaveHint = AndroidHelper$ToDart$Companion._class
      .instanceMethodId(
        r'getOnUserLeaveHint',
        r'()Ljava/lang/Runnable;',
      );

  static final _get$onUserLeaveHint =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Runnable getOnUserLeaveHint()`
  /// The returned object must be released after use, by calling the [release] method.
  Runnable? get onUserLeaveHint {
    final _$$selfRef = reference;
    return _get$onUserLeaveHint(
      _$$selfRef.pointer,
      _id_get$onUserLeaveHint.pointer,
    ).object<Runnable?>();
  }

  static final _id_set$onUserLeaveHint = AndroidHelper$ToDart$Companion._class
      .instanceMethodId(
        r'setOnUserLeaveHint',
        r'(Ljava/lang/Runnable;)V',
      );

  static final _set$onUserLeaveHint =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setOnUserLeaveHint(java.lang.Runnable runnable)`
  set onUserLeaveHint(Runnable? runnable) {
    final _$$selfRef = reference;
    final _$runnable = runnable?.reference ?? jni$_.jNullReference;
    _set$onUserLeaveHint(
      _$$selfRef.pointer,
      _id_set$onUserLeaveHint.pointer,
      _$runnable.pointer,
    ).check();
  }

  static final _id_get$onConfigurationChanged = AndroidHelper$ToDart$Companion
      ._class
      .instanceMethodId(
        r'getOnConfigurationChanged',
        r'()Ljava/lang/Runnable;',
      );

  static final _get$onConfigurationChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Runnable getOnConfigurationChanged()`
  /// The returned object must be released after use, by calling the [release] method.
  Runnable? get onConfigurationChanged {
    final _$$selfRef = reference;
    return _get$onConfigurationChanged(
      _$$selfRef.pointer,
      _id_get$onConfigurationChanged.pointer,
    ).object<Runnable?>();
  }

  static final _id_set$onConfigurationChanged = AndroidHelper$ToDart$Companion
      ._class
      .instanceMethodId(
        r'setOnConfigurationChanged',
        r'(Ljava/lang/Runnable;)V',
      );

  static final _set$onConfigurationChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setOnConfigurationChanged(java.lang.Runnable runnable)`
  set onConfigurationChanged(Runnable? runnable) {
    final _$$selfRef = reference;
    final _$runnable = runnable?.reference ?? jni$_.jNullReference;
    _set$onConfigurationChanged(
      _$$selfRef.pointer,
      _id_set$onConfigurationChanged.pointer,
      _$runnable.pointer,
    ).check();
  }
}

final class $AndroidHelper$ToDart$Companion$Type$
    extends jni$_.JType<AndroidHelper$ToDart$Companion> {
  @jni$_.internal
  const $AndroidHelper$ToDart$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/piliplus/AndroidHelper$ToDart$Companion;';
}

/// from: `com.example.piliplus.AndroidHelper$ToDart`
extension type AndroidHelper$ToDart._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/piliplus/AndroidHelper$ToDart',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AndroidHelper$ToDart> type =
      $AndroidHelper$ToDart$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/example/piliplus/AndroidHelper$ToDart$Companion;',
  );

  /// from: `static public final com.example.piliplus.AndroidHelper$ToDart$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static AndroidHelper$ToDart$Companion get Companion =>
      _id_Companion.get(_class, AndroidHelper$ToDart$Companion.type)
          as AndroidHelper$ToDart$Companion;

  static final _id_get$onUserLeaveHint = _class.staticMethodId(
    r'getOnUserLeaveHint',
    r'()Ljava/lang/Runnable;',
  );

  static final _get$onUserLeaveHint =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final java.lang.Runnable getOnUserLeaveHint()`
  /// The returned object must be released after use, by calling the [release] method.
  static Runnable? get onUserLeaveHint {
    final _$$classRef = _class.reference;
    return _get$onUserLeaveHint(
      _$$classRef.pointer,
      _id_get$onUserLeaveHint.pointer,
    ).object<Runnable?>();
  }

  static final _id_set$onUserLeaveHint = _class.staticMethodId(
    r'setOnUserLeaveHint',
    r'(Ljava/lang/Runnable;)V',
  );

  static final _set$onUserLeaveHint =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void setOnUserLeaveHint(java.lang.Runnable runnable)`
  static set onUserLeaveHint(Runnable? runnable) {
    final _$$classRef = _class.reference;
    final _$runnable = runnable?.reference ?? jni$_.jNullReference;
    _set$onUserLeaveHint(
      _$$classRef.pointer,
      _id_set$onUserLeaveHint.pointer,
      _$runnable.pointer,
    ).check();
  }

  static final _id_get$onConfigurationChanged = _class.staticMethodId(
    r'getOnConfigurationChanged',
    r'()Ljava/lang/Runnable;',
  );

  static final _get$onConfigurationChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final java.lang.Runnable getOnConfigurationChanged()`
  /// The returned object must be released after use, by calling the [release] method.
  static Runnable? get onConfigurationChanged {
    final _$$classRef = _class.reference;
    return _get$onConfigurationChanged(
      _$$classRef.pointer,
      _id_get$onConfigurationChanged.pointer,
    ).object<Runnable?>();
  }

  static final _id_set$onConfigurationChanged = _class.staticMethodId(
    r'setOnConfigurationChanged',
    r'(Ljava/lang/Runnable;)V',
  );

  static final _set$onConfigurationChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void setOnConfigurationChanged(java.lang.Runnable runnable)`
  static set onConfigurationChanged(Runnable? runnable) {
    final _$$classRef = _class.reference;
    final _$runnable = runnable?.reference ?? jni$_.jNullReference;
    _set$onConfigurationChanged(
      _$$classRef.pointer,
      _id_set$onConfigurationChanged.pointer,
      _$runnable.pointer,
    ).check();
  }
}

final class $AndroidHelper$ToDart$Type$
    extends jni$_.JType<AndroidHelper$ToDart> {
  @jni$_.internal
  const $AndroidHelper$ToDart$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/piliplus/AndroidHelper$ToDart;';
}

/// from: `com.example.piliplus.AndroidHelper`
extension type AndroidHelper._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/piliplus/AndroidHelper',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AndroidHelper> type = $AndroidHelper$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/example/piliplus/AndroidHelper$Companion;',
  );

  /// from: `static public final com.example.piliplus.AndroidHelper$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static AndroidHelper$Companion get Companion =>
      _id_Companion.get(_class, AndroidHelper$Companion.type)
          as AndroidHelper$Companion;

  static final _id_get$isFoldable = _class.staticMethodId(
    r'isFoldable',
    r'()Z',
  );

  static final _get$isFoldable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final boolean isFoldable()`
  static core$_.bool get isFoldable {
    final _$$classRef = _class.reference;
    return _get$isFoldable(
      _$$classRef.pointer,
      _id_get$isFoldable.pointer,
    ).boolean;
  }

  static final _id_set$foldable = _class.staticMethodId(
    r'setFoldable',
    r'(Z)V',
  );

  static final _set$foldable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final void setFoldable(boolean z)`
  static set foldable(core$_.bool z) {
    final _$$classRef = _class.reference;
    _set$foldable(
      _$$classRef.pointer,
      _id_set$foldable.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_back = _class.staticMethodId(
    r'back',
    r'()V',
  );

  static final _back =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final void back()`
  static void back() {
    final _$$classRef = _class.reference;
    _back(_$$classRef.pointer, _id_back.pointer).check();
  }

  static final _id_biliSendCommAntifraud = _class.staticMethodId(
    r'biliSendCommAntifraud',
    r'(IJIJJJJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)V',
  );

  static final _biliSendCommAntifraud =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void biliSendCommAntifraud(int i, long j, int i1, long j1, long j2, long j3, long j4, java.lang.String string, java.lang.String string1, java.lang.String string2, long j5, java.lang.String string3)`
  static void biliSendCommAntifraud(
    core$_.int i,
    core$_.int j,
    core$_.int i1,
    core$_.int j1,
    core$_.int j2,
    core$_.int j3,
    core$_.int j4,
    jni$_.JString string,
    jni$_.JString? string1,
    jni$_.JString string2,
    core$_.int j5,
    jni$_.JString string3,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    _biliSendCommAntifraud(
      _$$classRef.pointer,
      _id_biliSendCommAntifraud.pointer,
      i,
      j,
      i1,
      j1,
      j2,
      j3,
      j4,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      j5,
      _$string3.pointer,
    ).check();
  }

  static final _id_openLinkVerifySettings = _class.staticMethodId(
    r'openLinkVerifySettings',
    r'()V',
  );

  static final _openLinkVerifySettings =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final void openLinkVerifySettings()`
  static void openLinkVerifySettings() {
    final _$$classRef = _class.reference;
    _openLinkVerifySettings(
      _$$classRef.pointer,
      _id_openLinkVerifySettings.pointer,
    ).check();
  }

  static final _id_openMusic = _class.staticMethodId(
    r'openMusic',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z',
  );

  static final _openMusic =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final boolean openMusic(java.lang.String string, java.lang.String string1, java.lang.String string2)`
  static core$_.bool openMusic(
    jni$_.JString string,
    jni$_.JString? string1,
    jni$_.JString? string2,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    return _openMusic(
      _$$classRef.pointer,
      _id_openMusic.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
    ).boolean;
  }

  static final _id_setPipAutoEnterEnabled = _class.staticMethodId(
    r'setPipAutoEnterEnabled',
    r'(ZJ)V',
  );

  static final _setPipAutoEnterEnabled =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int64)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `static public final void setPipAutoEnterEnabled(boolean z, long j)`
  static void setPipAutoEnterEnabled(
    core$_.bool z,
    core$_.int j,
  ) {
    final _$$classRef = _class.reference;
    _setPipAutoEnterEnabled(
      _$$classRef.pointer,
      _id_setPipAutoEnterEnabled.pointer,
      z ? 1 : 0,
      j,
    ).check();
  }

  static final _id_maxScreenSize = _class.staticMethodId(
    r'maxScreenSize',
    r'()[I',
  );

  static final _maxScreenSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final int[] maxScreenSize()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JIntArray? maxScreenSize() {
    final _$$classRef = _class.reference;
    return _maxScreenSize(
      _$$classRef.pointer,
      _id_maxScreenSize.pointer,
    ).object<jni$_.JIntArray?>();
  }
}

final class $AndroidHelper$Type$ extends jni$_.JType<AndroidHelper> {
  @jni$_.internal
  const $AndroidHelper$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/piliplus/AndroidHelper;';
}

/// from: `kotlin.Pair`
extension type Pair<$A extends jni$_.JObject?, $B extends jni$_.JObject?>._(
  jni$_.JObject _$this
) implements jni$_.JObject, Serializable {
  static final _class = jni$_.JClass.forName(r'kotlin/Pair');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Pair> type = $Pair$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/Object;Ljava/lang/Object;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(A object, B object1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Pair(
    $A? object,
    $B? object1,
  ) {
    final _$$classRef = _class.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<Pair<$A, $B>>();
  }
}

extension Pair$$Methods<$A extends jni$_.JObject?, $B extends jni$_.JObject?>
    on Pair<$A, $B> {
  static final _id_get$first = Pair._class.instanceMethodId(
    r'getFirst',
    r'()Ljava/lang/Object;',
  );

  static final _get$first =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final A getFirst()`
  /// The returned object must be released after use, by calling the [release] method.
  $A? get first {
    final _$$selfRef = reference;
    return _get$first(_$$selfRef.pointer, _id_get$first.pointer).object<$A?>();
  }

  static final _id_get$second = Pair._class.instanceMethodId(
    r'getSecond',
    r'()Ljava/lang/Object;',
  );

  static final _get$second =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final B getSecond()`
  /// The returned object must be released after use, by calling the [release] method.
  $B? get second {
    final _$$selfRef = reference;
    return _get$second(
      _$$selfRef.pointer,
      _id_get$second.pointer,
    ).object<$B?>();
  }

  static final _id_toString$1 = Pair._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    final _$$selfRef = reference;
    return _toString$1(
      _$$selfRef.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_component1 = Pair._class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/Object;',
  );

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): A`
  /// The returned object must be released after use, by calling the [release] method.
  $A? component1() {
    final _$$selfRef = reference;
    return _component1(
      _$$selfRef.pointer,
      _id_component1.pointer,
    ).object<$A?>();
  }

  static final _id_component2 = Pair._class.instanceMethodId(
    r'component2',
    r'()Ljava/lang/Object;',
  );

  static final _component2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component2(): B`
  /// The returned object must be released after use, by calling the [release] method.
  $B? component2() {
    final _$$selfRef = reference;
    return _component2(
      _$$selfRef.pointer,
      _id_component2.pointer,
    ).object<$B?>();
  }

  static final _id_copy = Pair._class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;',
  );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(first: A, second: B): kotlin.Pair<A, B>`
  /// The returned object must be released after use, by calling the [release] method.
  Pair<$A?, $B?> copy(
    $A? object,
    $B? object1,
  ) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _copy(
      _$$selfRef.pointer,
      _id_copy.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<Pair<$A?, $B?>>();
  }

  static final _id_hashCode$1 = Pair._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_equals = Pair._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(
    jni$_.JObject? object,
  ) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }
}

final class $Pair$Type$ extends jni$_.JType<Pair> {
  @jni$_.internal
  const $Pair$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/Pair;';
}

/// from: `java.lang.Runnable`
extension type Runnable._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'java/lang/Runnable');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Runnable> type = $Runnable$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $Runnable> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'run()V') {
        _$impls[$p]!.run();
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $Runnable $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'java.lang.Runnable',
      $p,
      _$invokePointer,
      [
        if ($impl.run$async) r'run()V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory Runnable.implement(
    $Runnable $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<Runnable>();
  }
}

extension Runnable$$Methods on Runnable {
  static final _id_run = Runnable._class.instanceMethodId(
    r'run',
    r'()V',
  );

  static final _run =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract void run()`
  void run() {
    final _$$selfRef = reference;
    _run(_$$selfRef.pointer, _id_run.pointer).check();
  }
}

abstract base mixin class $Runnable {
  factory $Runnable({
    required void Function() run,
    core$_.bool run$async,
  }) = _$Runnable;

  void run();
  core$_.bool get run$async => false;
}

final class _$Runnable with $Runnable {
  _$Runnable({
    required void Function() run,
    this.run$async = false,
  }) : _run = run;

  final void Function() _run;
  final core$_.bool run$async;

  void run() {
    return _run();
  }
}

final class $Runnable$Type$ extends jni$_.JType<Runnable> {
  @jni$_.internal
  const $Runnable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Runnable;';
}

/// from: `kotlin.jvm.internal.DefaultConstructorMarker`
///
/// WARNING: DefaultConstructorMarker is a stub. To generate bindings for this class, include
/// kotlin.jvm.internal.DefaultConstructorMarker in your config's classes list.
///
extension type DefaultConstructorMarker._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<DefaultConstructorMarker> type =
      $DefaultConstructorMarker$Type$();
}

final class $DefaultConstructorMarker$Type$
    extends jni$_.JType<DefaultConstructorMarker> {
  @jni$_.internal
  const $DefaultConstructorMarker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/jvm/internal/DefaultConstructorMarker;';
}

/// from: `java.io.Serializable`
///
/// WARNING: Serializable is a stub. To generate bindings for this class, include
/// java.io.Serializable in your config's classes list.
///
extension type Serializable._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Serializable> type = $Serializable$Type$();
}

final class $Serializable$Type$ extends jni$_.JType<Serializable> {
  @jni$_.internal
  const $Serializable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/io/Serializable;';
}
