name: Build for Mac

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      branch:
        required: false
        default: "main"

jobs:
  build-mac-app:
    name: Release Mac
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Build Mac
        run: flutter build macos --release --dart-define-from-file=pili_release.json --build-name="${{ env.version }}" --build-number="${{ env.number }}"

      - name: Prepare Upload
        run: |
          npm install --global create-dmg
          create-dmg build/macos/Build/Products/Release/PiliPlus.app
        continue-on-error: true

      - name: Rename DMG
        run: mv PiliPlus*.dmg PiliPlus_macos_${{ env.version }}.dmg

      - name: Upload macos release
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: PiliPlus*.dmg
